;ENUNCIADO DEL PROBLEMA
;PRÁCTICA 5: DECODIFICADOR DE 0-F
;REALICE UN PROGRAMA PARA EL PIC16F887, CON EL PUERTO A CONFIGURADO COMO ENTRADA DIGITAL 
;Y EL B COMO SALIDA. LOS 4 BITS MENOS SIGNIFICATIVOS DEL PUERTO A, DETERMINARÁN EL DÍGITO 
;QUE SE MOSTRARÁ EN EL DISPLAY DE 7 SEGMENTOS QUE SE CONECTARÁ EN EL PUERTO B. POR EJEMPLO, 
;SI EN LA ENTRADA SE INTRODUCE EL 0101, EN LA SALIDA DEBERÁ MOSTRARSE EL 5. USAR TABLA DE DATOS.
;INTEGRANTES:
;ANDRADE SALAZAR IGNACIO
;ORTIZ JIMENEZ VLADIMIR
;GUERRERO SANTANA EDGAR GEOVANNY
;FECHA: 09/10/2023

			LIST P=16F887			;ELEGIR EL PIC
			INCLUDE "P16F887.INC"	;CARGA LA LIBRERIA DEL PIC
			;CONTA	EQU	0X20			
			ORG 	0X00			;INDICA EL ORIGEN DEL PROG
			GOTO	INICIO			;SALTAR A LA ETIQUETA INICIO
INICIO
			BSF	STATUS,RP0			;PONE EN 1 RP0 DEL STATUS
			BSF	STATUS,RP1			;PONE EN 1 RP1 DEL STATUS
									;ESTAS DOS INSTRUCCIONES NOS MANDADN AL BANCO 3
			CLRF	PORTB			;PORTA COMO IN/OUT DIGITAL
			CLRF	ANSEL			;PORTB COMO IN/OUT DIGITAL
			CLRF	ANSELH			;PORTB CONFIGURADO COMO OUT
			BCF	STATUS,RP0			;PONE EN 0 RP0 DEL STATUS
			BCF	STATUS,RP1			;PONE EN 0 RP1 DEL STATUS									
									;MANDAN AL BANCO 0
START 
			MOVF	PORTA,W			;LEER PRTA -> W
			ANDLW 	B'00001111'		;MULTIPLICAR MASCARA, OBTENEMOS EL VALOR
			CALL 	DISPLAY
			MOVWF 	PORTB
			GOTO 	START

DISPLAY 
			ADDWF PCL, F
			;	0    1	  2    3     4   5    6    7    8    9    A     B   C     D   E    F
			DT 0x3F,0X06,0X5B,0x4F,0x66,0x6D,0x7D,0x07,0x7F,0x6F,0x77,0x7C,0X39,0x5E,0x79,0x71 
			END