;Enunciado del problema
;PRACTICA 6
;REALICE UN PROGRAMA PARA EL PIC16F887 CON EL PUERTO A CONFIGURADO COMO ENTRADA DIGITAL Y EL PUERTO B
;COMO SALIDA. DEBERÁ ENCENDER Y APAGAR EL LED RC1 CON UNA FRECUENCIA VISIBLE. ESO DEBERÁ OCURRIR CUANDO 
;UN BIT DEL PUERTO A ESTÉ EN 1, SI SE PONE EN 0, SE DEBE APAGAR EL LED
;INTEGRANTES:
;ANDRADE SALAZAR IGNACIO
;ORTIZ JIMENEZ VLADIMIR
;GUERRERO SANTANA EDGAR GEOVANNY
;FECHA: 30/10/2023

			LIST P=16F887		;ELEGIR EL PIC
			INCLUDE "P16F887.INC"	;CARGA LA LIBRERIA DEL PIC
R0 	EQU	0X20
R1 	EQU	0X21
R2 	EQU	0X22
			ORG 	0X00		;INDICA EL ORIGEN DEL PROG
			GOTO	INICIO		;SALTAR A LA ETIQUETA INICIO
INICIO
			BSF	STATUS,RP0	;PONE EN 1 RP0 DEL STATUS
			BSF	STATUS,RP1	;PONE EN 1 RP1 DEL STATUS
			;ESTAS DOS INSTRUCCIONES NOS MANDADN AL BANCO 3
			CLRF	PORTB		;PORTA COMO IN/OUT DIGITAL
			CLRF	ANSEL		;PORTB COMO IN/OUT DIGITAL
			CLRF	ANSELH		;PORTB CONFIGURADO COMO OUT
			BCF	STATUS,RP0	;PONE EN 0 RP0 DEL STATUS
			BCF	STATUS,RP1	;PONE EN 0 RP1 DEL STATUS									
			;MANDAN AL BANCO 0

LEER		MOVF 		PORTA,W		;MOVER PORTA -> W	
			XORLW		0X00		;HACER LA COMPARACIÓN DE VALORES
			BTFSS		STATUS,Z	;CHECAR SI BIT Z = 1, DATO CORRECTO
			GOTO	ENCENDER
			GOTO	APAGAR

LEER2		MOVF 		PORTA,W		;MOVER PORTA -> W	
			XORLW		0X00		;HACER LA COMPARACIÓN DE VALORES
			BTFSS		STATUS,Z	;CHECAR SI BIT Z = 1, DATO CORRECTO
			GOTO	ENCENDER2
			GOTO	APAGAR

ENCENDER	BSF	PORTB,0				;ENCENDER BIT PORQUE LA CONTRASEÑA ES CORRECTA
			BSF	PORTB,1
			BSF	PORTB,2
			BSF	PORTB,3
			BCF	PORTB,4
			BCF	PORTB,5
			BCF	PORTB,6
			BCF	PORTB,7
			CALL	TIME
			GOTO 	LEER2

ENCENDER2	BCF	PORTB,0
			BCF	PORTB,1
			BCF	PORTB,2
			BCF	PORTB,3
			BSF	PORTB,4
			BSF	PORTB,5
			BSF	PORTB,6
			BSF	PORTB,7
			CALL	TIME
			GOTO	LEER

APAGAR		BCF	PORTB,0
			BCF	PORTB,1
			BCF	PORTB,2
			BCF	PORTB,3
			BCF	PORTB,4
			BCF	PORTB,5
			BCF	PORTB,6
			BCF	PORTB,7
			GOTO 	LEER			

TIME			MOVLW	.100
			MOVWF	R0
			MOVLW	.50
			MOVWF	R1
			MOVLW	.2
			MOVWF	R2

AQUI			DECFSZ	R0,F
			GOTO	AQUI
			DECFSZ	R1,F
			GOTO	AQUI
			DECFSZ	R2,F
			GOTO	AQUI
			RETURN
			END